CREATE TABLE TB_ROOM (
    ID      BIGINT          NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR (50)    NOT NULL,
    SEATS   INT             NOT NULL,
    STATUS  TINYINT         NOT NULL,

    PRIMARY KEY (ID)
)   ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4;
